# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.CharField(max_length=20)),
                ('Event_name', models.CharField(max_length=100)),
                ('Event_description', models.CharField(max_length=100)),
                ('Date_of_registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('Date_of_Event', models.DateTimeField(default=django.utils.timezone.now)),
                ('Lastdate_of_registration', models.DateTimeField(default=models.DateTimeField(default=django.utils.timezone.now))),
            ],
        ),
    ]
