# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_id',
        ),
    ]
