# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=50)),
                ('Event_id', models.CharField(max_length=50)),
                ('Employee_Registered_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
