# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registered_Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_events',
            name='Emp_id',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='registered_events',
            name='Event_id',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
